const $=s=>document.querySelector(s),weekday=["一","二","三","四","五","六","日"],today=new Date();
const dateKey=d=>{const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,10)};const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
async function api(path,options){const response=await fetch(`http://127.0.0.1:8765${path}`,options);const payload=await response.json();if(!response.ok)throw new Error(payload.error||`HTTP ${response.status}`);return payload}
async function invokeDesktop(command){const invoke=window.__TAURI_INTERNALS__?.invoke;if(invoke)await invoke(command)}
document.querySelectorAll("[data-window-action]").forEach(button=>button.onclick=()=>{const action=button.dataset.windowAction;invokeDesktop(action==="minimize"?"minimize_window":action==="maximize"?"toggle_maximize":"close_window")});document.querySelectorAll(".muted-link,.quick-card.disabled").forEach(item=>item.onclick=e=>e.preventDefault());
function renderHeader(){$("#weekday").textContent=weekday[(today.getDay()+6)%7];$("#today").textContent=today.toLocaleDateString("zh-CN",{month:"long",day:"numeric"});$("#day-number").textContent=today.getDate();$("#month-label").textContent=today.toLocaleDateString("zh-CN",{month:"long"})}
function renderAgenda(events){$("#agenda-count").textContent=events.length;$("#agenda-list").innerHTML=events.length?events.slice(0,5).map(event=>{const start=new Date(event.starts_at);return `<div class="agenda-item"><div class="agenda-time">${start.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</div><i class="agenda-dot"></i><div class="agenda-main"><b>${escapeHtml(event.title)}</b><small>${escapeHtml(event.location||"无地点")}</small></div></div>`}).join(""):"<div class=\"empty\">今天还没有安排，给自己留一点空间。</div>"}
function renderTodos(items){const open=items.filter(item=>!item.completed);$("#todo-count").textContent=open.length;$("#todo-progress").style.width=`${items.length?Math.round((items.length-open.length)/items.length*100):0}%`;$("#todo-list").innerHTML=open.slice(0,5).length?open.slice(0,5).map(item=>`<div class="todo-item" data-id="${escapeHtml(item.id)}"><button class="todo-check" title="完成">✓</button><div class="todo-main"><b>${escapeHtml(item.title)}</b><small>${item.due_at?`截止 ${new Date(item.due_at).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"})}`:"暂无截止时间"}</small></div></div>`).join(""):"<div class=\"empty\">今天没有待办，状态不错。</div>";document.querySelectorAll(".todo-check").forEach(button=>button.onclick=async()=>{const id=button.closest(".todo-item").dataset.id;await api(`/api/todos?id=${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed:true})});load()})}
function monday(date){const result=new Date(date);result.setDate(result.getDate()-((result.getDay()+6)%7));result.setHours(0,0,0,0);return result}
function renderClasses(courses){$("#course-count").textContent=courses.length;$("#semester").textContent=courses[0]?.semester||"未设置学期";const start=monday(today);$("#week-grid").innerHTML=Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);const sessions=courses.flatMap(course=>course.sessions.filter(session=>session.weekday===index+1).map(session=>({course,session})));return `<div class="day ${dateKey(date)===dateKey(today)?"today":""}"><div class="day-head"><span>周${weekday[index]}</span><strong>${date.getDate()}</strong></div>${sessions.slice(0,2).map(({course,session})=>`<div class="class-chip"><b>${escapeHtml(course.name)}</b><small>${session.start_time?.slice(0,5)||`第${session.start_period}节`}</small></div>`).join("")||"<div class=\"empty\">无课</div>"}</div>`}).join("")}
async function load(){try{const [calendar,todos,courses]=await Promise.all([api(`/api/calendar?start=${dateKey(today)}T00:00:00%2B08:00&end=${dateKey(new Date(today.getTime()+7*86400000))}T23:59:59%2B08:00`),api("/api/todos"),api("/api/courses")]);renderAgenda(calendar.events.filter(event=>new Date(event.starts_at).toDateString()===today.toDateString()));renderTodos(todos.todos);renderClasses(courses.courses);$("#updated").textContent=`更新于 ${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`}catch(error){$("#agenda-list").innerHTML=`<div class="empty">本地服务尚未连接：${escapeHtml(error.message)}</div>`}}
$("#add-event").onclick=()=>window.location.href="http://127.0.0.1:8765/#calendar";$("#add-todo").onclick=()=>window.location.href="http://127.0.0.1:8765/#todos";renderHeader();load();setInterval(load,30000);
